### ISSUE TITLE
Incompatible with 1.19.2 Quilt

### ISSUE THREAD

**Issue by p3lim** [otomir23/SootyChimneysFabric#3]
You've set a hard dependency on [Fabric Language Kotlin v1.9.6+kotlin.1.8.22](https://modrinth.com/mod/fabric-language-kotlin/version/1.9.6+kotlin.1.8.22) for version 1.0.2 of your mod (the latest available), whereas the last kotlin version of [Quilt Kotlin Libraries (QLK)](https://modrinth.com/mod/qkl/versions?g=1.19.2) for 1.19.2 is 1.8.0 (QLK 1.0.2+kt.1.8.0+flk.1.9.0).

I don't know if you have a requirement for later patch levels of the kotlin libraries in your mod, if you care about support for people running Quilt as their modloader, or if you even care to keep the 1.19.2 version of your mod functioning now that 1.20.x is out, but if you could fix this that'd be great. If you don't intend to continue support for 1.19.2 that is also understandable.

**Comment by otomir23** [comment]
Thanks for the suggestion! I will try my best to resolve this.

**Comment by otomir23** [comment]
Fixed in 1.0.3 for 1.19.2. I'm not currently planning to port rewrites and optimizations from 1.1.0+ fot 1.20.1, but happy to help with bugs and issues.

**Comment by p3lim** [comment]
Thanks for the quick fix, I'm not expecting new features at all for this version, but a compatibility fix like this is nice to see :+1:.
